site_name: 'Spring Demo Doc'
site_url: 'https://jibanezmico.github.io/spring-demo'
site_author: 'Javi Ibáñez'
site_description: 'Documentación sobre la demo de Spring'

theme:
  features:
    - content.action.edit
    - content.action.view
#    - navigation.tabs
#    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  font:
    text: 'Roboto'
  markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
  # google_analytics:
  #   property: 'UA-12345678-9'
  #   auto: true

nav:
  - Home: index.md
  - Introducción a Spring Boot y conceptos clave: 0_introduccion.md
  - Configuración del Proyecto: 1_configuracion.md
  - Introducción a Spring Web: 2_spring_web.md
  - Gestión de Datos y Lógica de Negocio con Spring Data: 3_spring_data.md
  - Seguridad con Spring Security y JWT: 4_spring_security.md
  - Documentación con Swagger: 5_swagger.md
  - Implementación de Servicios en Red: 6_servcios_red.md
  - Pruebas y Depuración: 7_test.md
  - Introducción a la programación distribuida: 8_distribuida.md
  - Despliegue de Aplicaciones Spring Boot en Entornos de Producción: 9_despliegue.md

plugins:
  - search
  - macros

extra_css:
  - 'styles/extra.css'
# extra_javascript:
#   - 'js/custom.js'

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: 'https://github.com/jibanezmico/spring-demo'
repo_name: 'spring-demo'
edit_uri: 'edit/main/spring-demo-doc/docs/'

use_directory_urls: true
strict: true
